### ISSUE TITLE
This demo is pure gold. createContext not exported member of react

### ISSUE THREAD

**Issue by KoderFPV** [kentcdodds/super-simple-rsc#1]
Hi,

This demo app is super awesome. Excellent skills showcase of deep understanding react itself. Literally, no dependencies is mind-blowing.

However, when trying to start app I got an error

![image](https://github.com/kentcdodds/super-simple-rsc/assets/7673542/d67ae506-2adc-436f-923a-d091909529ca)

We also have problems with context in the case of RSC in our project, and as usual `use client` directive at the top of file didn't help.
Do you know how to solve this kind of issue?

Thanks anyway for makes react ecosystem better place on earth :)

**Comment by kentcdodds** [comment]
Hi @KoderFPV!

I should update the README for this project. I turned it into a workshop. You can see the material here: https://github.com/epicweb-dev/react-server-components

Much better learning experience there!
